### ISSUE TITLE
Add support for Preview Review Requests API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#516] opened 2017-01-12 17:30 UTC
Announcement:
https://developer.github.com/changes/2016-12-16-review-requests-api/

**Comment by shurcooL** [comment] 2017-01-12 20:03
Imagine the struct for "create a review request" endpoint options being named... `PullRequestReviewRequestRequest`. 😆

**Comment by gmlewis** [comment] 2017-01-12 20:06
Looks like Java in Go!  :smile:

**Comment by varadarajana** [comment] 2017-01-14 18:33
If this has not been assigned earlier, please assign it to me, I can work on it, as my integration tests are almost complete.

**Comment by varadarajana** [comment] 2017-02-17 15:55
@gmlewis if this is not assigned already, please assign it to me. I am almost done with #530

**Comment by shurcooL** [comment] 2017-02-21 22:50
It looks like #557 is related.

@varadarajana, @sevki, you should coordinate to avoid duplicate work.

**Comment by varadarajana** [comment] 2017-02-26 05:55
@shurcooL this PR can be closed, as it is duplicate of #557

**Comment by shurcooL** [comment] 2017-02-27 21:16
It's not a duplicate issue because #557 is a PR, not an issue. The issue tracks the completion of the relevant functionality. It shouldn't be closed until this functionality is implemented.

#557 is a PR that will resolve this issue.

**Closed** 2017-03-08 00:44 UTC
