### ISSUE TITLE
Interfacing the github Client

### ISSUE THREAD

**Issue by Brian-McM** [google/go-github#1596] opened 2020-08-12 17:05 UTC
Hi,
I'm about to start writing tests for some code that uses the github Client and I realised that the Client isn't interfaced and requires accessing the exported fields directly, which are also not interfaced. This makes it very difficult to mock the Client for testing purposes. I can, and probably will, just mock the http request for the client but that's definitely more work then just mocking out the functions that my tests are using and it also means that I can't take advantage of the parameter verification that testing tools like testify provide.

It would be nice if future iterations moved towards interfacing the client.

**Comment by gmlewis** [comment] 2020-08-14 13:02
I write unit tests against this repo frequently and make a new interface in my client code for just the functions that I want to mock.

We purposefully don't write interfaces on the repo side because then your client code that you are trying to test would need to implement mocks for every method within the interface which would be a huge drag.

So this is working as intended.

Closing.

**Closed by gmlewis** 2020-08-14 13:02 UTC

**Comment by EzioPatil** [comment] 2024-12-23 08:33
hello
