### ISSUE TITLE
RepoStatus.id needs to be int64

### ISSUE THREAD

**Issue by maruel** [google/go-github#806] opened 2017-12-10 14:40 UTC
[RepoStatus.ID](https://godoc.org/github.com/google/go-github/github#RepoStatus) is *int but it must be int64. When calling [RepositoriesService.CreateStatus()](https://godoc.org/github.com/google/go-github/github#RepositoriesService.CreateStatus), the call fails with:
```
json: cannot unmarshal number 4396447431 into Go struct field RepoStatus.id of type int
```

It broke [gohci](https://github.com/periph/gohci) which is used for https://periph.io.

**Comment by maruel** [comment] 2017-12-10 14:42
I probably observed it first because the gohci workers are built with 32 bits Go (on ARM), 64 bits Go executables are probably not affected.

**Comment by shurcooL** [comment] 2017-12-10 16:06
Thanks for reporting. This is definitely related to #597.

**Comment by maruel** [comment] 2017-12-10 16:41
Thanks, indeed. Sorry I searched for "RepoStatus" but didn't search for "int64" prior filing. My bad.

In practice I worked around my immediate problem so it is not urgent for me anymore but in practice this means no user of the library can use the CreateStatus API on a 32 bits executable right now.

**Comment by shurcooL** [comment] 2017-12-14 22:21
Thanks for the valuable report @maruel. I'll close this as duplicate of #597, make a reference to it there (because there's useful data here) so we have a single centralized place to discuss this issue and make a decision.

**Closed by shurcooL** 2017-12-14 22:21 UTC
Labels: duplicate
