### ISSUE TITLE
Deployment Payload field is double-encoded in responses

### ISSUE THREAD

**Issue by tragiclifestories** [google/go-github#1116] opened 2019-02-11 13:13 UTC
Hi all, I've run into slight ergonomics issue.

The Github deployments API has a field called `payload` which is an arbitrary JSON object encoded into a string.
```json
{
    "repo": "foo",
    "owner": "bar",
    "payload": "{\"run_acceptance_tests\": true}"
}
```

If I access this from, for example, Octokit in Ruby, I get the string I put in.

```ruby
payload = client.
  deployments(owner: "tragiclifestories", repo: "my-awesome-ruby-app").
  first.
  payload
# => "{\"run_acceptance_tests\": true}"

payload[0]
# => "{"
```

With go-github, however, the `Payload` field of the returned `github.Deployment` struct is double-encoded.

```go
deployments, _, _ := d.Repositories.ListDeployments(
	ctx,
	"tragiclifestories",
	"my-awesome-go-app",
)

payload := deployments[0].GetPayload()

fmt.Printf("%s\n", string(payload))     // `"{\"run_acceptance_tests\": true}"`
fmt.Printf("%s\n", string(payload[:1])) // `"`
```

This makes unmarshaling a bit more hassly than in comparable clients.

```
type myStruct struct {
	RunAcceptanceTests bool `json:"run_acceptance_tests"`
}

var payloadJSON string

err := json.Unmarshal(payload, payloadJSON)
if err != nil {
	// whatever ...
}

myPayload = new(myStruct)

err := json.Unmarshal(payloadJSON, myPayload)

if err != nil {
	// whatever ...
}
```

As is clear from the above, there is a functional workaround. However, it seems wrong to me that this field has one value in the HTTP API and most other client library implementations, and another in the equivalent Go data structure.

**Comment by gmlewis** [comment] 2019-02-11 13:30
From the [Go docs](https://godoc.org/encoding/json#example-RawMessage--Unmarshal) for `json.RawMessage`, it looks like the implementation is correct as designed and is the result of using a strongly-typed language. Its purpose is to "delay JSON decoding" because it is not known ahead-of-time what its contents might be.

What do you recommend as a solution to this issue?

**Comment by tragiclifestories** [comment] 2019-02-11 13:52
Interesting - thanks for the link. 

You can see in that example the structure of the payload is slightly different.
```json
{
  "Space": "YCbCr",
  "Point": {
    "Y": 255,
    "Cb": 0,
    "Cr": -10
  }
}
```

With the response from the Github deployments API, we have the equivalent of:

```json
{
  "Space": "YCbCr",
  "Point": "{\"Y\": 255, \"Cb\": 0, \"Cr\": -10}"
}
```

So in the case of this API, we *do* know ahead-of-time what its contents might be - a string (or null).

So passing that to the RawMessage unmarshaling logic yields you a bytearray of a JSON string value (which must begin and end with a double-quote to be valid, of course). 

As to a solution, I don't have one that's super neat and tidy. The type of the Payload field could be changed to string, although it would then be necessary for callers to coerce to a bytearray or RawMessage later on which is not ideal. Alternatively the `GetPayload()` method could do the first unmarshal. There may be other approaches - I'm quite new to Go.

Obviously these are both breaking changes, but any 'fix' for this (if the maintainers believe it is a problem) must be by definition AFAICT.

**Comment by tragiclifestories** [comment] 2019-02-11 14:28
On further investigation, this may be an issue with Github's API docs.

They describe the field as such:

| name | type | description |
-------|------|--------------|
| payload | `string` | JSON payload with extra information about the deployment. Default: `""` |

However, it seems that you can actually set it to any arbitrary JSON sub-object you like.

```http
POST /repos/owner/proj/deployments
{
	"ref": "master",
	"task": "whatever",
	"auto_merge": false,
	"required_contexts": [],
	"payload": {"foo": 1}
}

200 (OK)
{
    "url": "https://api.github.com/repos/tragiclifestories/nicoticker/deployments/128291911",
    "id": 128291911,
    "node_id": "MDEwOkRlcGxveW1lbnQxMjgyOTE5MTE=",
    "sha": "29334456e01415c180f764ef6df2d1e66c91f558",
    "ref": "master",
    "task": "whatever",
    "payload": {
        "foo": 1
    },
...
```

It would be impossible to do this with the current implementation of  `CreateDeployment()` in this library, however, since the payload in the `DeploymentRequest` struct is a `*string` ...

**Comment by gmlewis** [comment] 2019-02-11 23:44
> It would be impossible to do this with the current implementation of `CreateDeployment()` in this library, however, since the payload in the `DeploymentRequest` struct is a `*string`

I don't understand this statement... what prevents you from marshaling the payload into the string `{"foo":1}` and sending that in the request?

**Comment by tragiclifestories** [comment] 2019-02-12 09:19
You can do that. However, the resulting payload is then:
```json
{
  "payload": "{\"foo\": 1}"
}
```

Unlike the previous example:

```json
{
  "payload": {
    "foo": 1
  }
}
```

The current implementation of `CreateDeployment()`, by insisting on a string pointer for the `Payload` field in the `DeploymentRequest` struct, will always result in the former. When that value is unmarshaled into a `json.RawValue`, however, the unmarshaling function will detect that the value is a string, and wrap it in double-quotes and backslash-escaping all double-quotes in the string so it is a valid JSON value. This leads to the issue where you have to decode it twice to get an actual usable value in the vast majority of cases.

If the `Payload` property in the `DeploymentRequest` struct were an `interface{}`, then you could shove arbitrary objects into it (as long as they can be marshaled into JSON), and then unmarshaling to `RawMessage` would make more sense (as per the docs you linked). I think that change would be backwards compatible as well.

I'm sorry if I'm not explaining this very well. I'm happy to make a PR for this but I don't want to do so if you or any other maintainers do not think there is a problem here.

**Comment by gmlewis** [comment] 2019-02-12 13:05
Oh, I think I understand now what you are saying... I apologize for my confusion.

It would be great if we could get others who have used this portion of the API to comment on their experience. In the meantime, I'll try out some examples with this... your `interface{}` suggestion sounds like it might be spot on, but I just want to try it out first.

**Comment by gmlewis** [comment] 2019-02-12 15:03
@tragiclifestories - please take a look at #1119 and see if this resolves the issue for you.
I originally didn't understand that this was a deployment *creation* issue, but now believe that it is.
Please correct me if I have misunderstood.

**Comment by tragiclifestories** [comment] 2019-02-12 15:31
I don't think I understood that either, to be honest! I've sort of worked it out as I've gone along. I will give it a try and get back to you ASAP, but it looks like it should solve our problem.

I might also file a support ticket with Github about the docs, which are incomplete at best on this point.

**Comment by gmlewis** [comment] 2019-06-14 12:59
Closing as obsolete. Feel free to reopen if there is demand.

**Comment by jrossiter** [comment] 2019-12-05 22:16
@gmlewis I'm running into this exact issue as well and was hoping https://github.com/google/go-github/pull/1119 was going to be merged.

We're trying to create a GitHub deployment using this library with a custom JSON payload. 
We're using GitHub actions workflows which cannot read the stringified JSON being sent in the trigger.

If you compare calling the GitHub API directly versus using this library you'll see the differences:

**Good: Calling the API directly: https://developer.github.com/v3/repos/deployments/#create-a-deployment**
```
// API Response:
{
  "url": "https://api.github.com/repos/octocat/example/deployments/1",
  "id": 1,

  ...

  "payload": {
    "foo": "bar"
  },

  ...
}

// GitHub Actions:
- run: echo "Event payload: ${{ github.event.deployment.payload.foo }}"
// This echoes "bar" as github.event.deployment.payload is a JSON object.
```

**Bad: Using github.Client: githubClient.Repositories.CreateDeployment()**
```
// API Response:
{
  "url": "https://api.github.com/repos/octocat/example/deployments/1",
  "id": 1,

  ...

  "payload": "{\"foo\": \"bar\"}"

  ...
}

// GitHub Actions:
- run: echo "Event payload: ${{ github.event.deployment.payload.foo }}"
// This echoes a blank string as github.event.deployment.payload is not a JSON object, it's a string.
```

**Comment by gmlewis** [comment] 2019-12-05 22:30
I've reopened #1119 and put out a call for volunteers to test out the PR before we proceed since there did not appear to be much interest before.

**Closed** 2019-12-23 19:24 UTC
