### ISSUE TITLE
Merged field in github.PullRequest produced by client.PullRequests.List(owner, repo, opt) is not filled in correctly

### ISSUE THREAD

**Issue by bruceauyeung** [google/go-github#496] opened 2016-12-16 03:01 UTC
i get a `[]*github.PullRequest` slice through invoking ` client.PullRequests.List(owner, repo, opt)`. but i found a strange thing. all PullRequests in this slice have field `Merged` with `nil` value , have field `MergedAt` with `nil` or non `nil` value based on the actual situation.

i think  field `Merged` should have a non nil value when `MergedAt` does.

commit 466070b0580728e63bd1a415e0019639e55d7148

**Comment by shurcooL** [comment] 2016-12-16 03:21
I think this is because there are less fields populated when you list pull requests. Try getting a single pull request, and I expect `Merged` will be populated then.

That's just what the GitHub API returns. Compare sample output of https://developer.github.com/v3/pulls/#list-pull-requests with https://developer.github.com/v3/pulls/#get-a-single-pull-request. The former contains "merged_at" field but not "merged". The latter contains both.

> commit 466070b0580728e63bd1a415e0019639e55d7148

What about it? Is it related to your question?

**Comment by bruceauyeung** [comment] 2016-12-16 12:37
>What about it? Is it related to your question?
this is the commit number of  go-github version i am using.

i don't understand why dont fill in `merged`  but `merged_at`. there is no performance penalty when filling in `merged` field. should we report this bug or situation to github API ?

**Comment by shurcooL** [comment] 2016-12-16 15:16
> this is the commit number of  go-github version i am using.

Ah, got it, thanks.

> i don't understand why dont fill in `merged`  but `merged_at`. there is no performance penalty when filling in `merged` field. should we report this bug or situation to github API ?

But there is. Imagine you get a list of 100 pull requests, then another 100, then another 100. The decision to leave some fields out when listing makes a bigger impact then.

Is `merged` the only field that's missing when listing pull requests? Or are there many others missing too?

If it's the only one, it's probably a bug. If there are many missin, I suspect it's as intended.

You can contact github support if you'd like to confirm.

**Comment by gmlewis** [comment] 2021-08-06 17:10
Closing issue for lack of activity/interest. Feel free to reopen.

**Closed by gmlewis** 2021-08-06 17:10 UTC
Labels: waiting for reply

**Comment by quinqu** [comment] 2021-11-16 00:52
I notice the same issue with the `MergeableState` field. When I list pull requests with `client.PullRequests.List`, that value is always nil. It seems this is intentional as there are multiple values missing. Just commenting for future folks.

**Comment by svyotov** [comment] 2022-04-22 16:52
MergedAt is nil for me too. I understand the performance issue, and I know others do it too, but my two cents are if it is always to be nil, what is the point in having it at all?

**Comment by gmlewis** [comment] 2022-04-22 17:22
> MergedAt is nil for me too. I understand the performance issue, and I know others do it too, but my two cents are if it is always to be nil, what is the point in having it at all?

The [request above](https://github.com/google/go-github/issues/496#issuecomment-267616043) is to have someone volunteer to contact GitHub v3 API tech support and ask them to clarify if it is always `nil`.  If so, we can remove it.  

Feel free to volunteer to do this, @svyotov and report back to this issue. Once we get a response, we can take further action if it makes sense.

Thanks!
