### ISSUE TITLE
User struct never contains an email

### ISSUE THREAD

**Issue by hartfordfive** [google/go-github#305] opened 2016-03-17 20:45 UTC
It seems like the `User` struct never contains a value for email, even when a given user's profile has a public email.

**Comment by willnorris** [comment] 2016-03-17 21:17
I wonder if maybe it's populated when viewing the current user with an oauth token that has email scope?

**Comment by shurcooL** [comment] 2016-03-18 05:27
Do you mean [`User.Email`](https://godoc.org/github.com/google/go-github/github#User.Email), the user's public email?

If so, I can't reproduce. Here's an example user with a public email:

https://api.github.com/users/mojombo

(Note that `"email"` is present.)

And here's what `UsersService.Get("mojombo")` returns:

![image](https://cloud.githubusercontent.com/assets/1924134/13869216/4872957e-ec8f-11e5-9cb0-2bcdc7a9d4d7.png)

Can you post more details on how to reproduce this?

**Comment by catchamonkey** [comment] 2016-07-20 19:56
I've seen this happen, and even if the user has a public email in their E-mails settings, unless it's configured in their profile (https://github.com/settings/profile) as shown, then it won't show up when fetching Users, in which case, you need to hit the ListEmails (/user/emails).

Hope that helps?

Though when calling ```githubClient.Users.ListEmails(nil)``` i'm just getting 404's, but that is a different issue of course!

**Comment by shurcooL** [comment] 2016-07-20 20:45
Hmm. The reported issue was that "User struct **never** contains an email" (emphasis mine), which I think https://github.com/google/go-github/issues/305#issuecomment-198214426 is a good counter-example proof.

If the email field was indeed never populated, then we could/should remove it. But if it's only populated some of the time but not always, there's nothing we need to change.

I think we should close this as not a bug.

**Closed** 2016-07-20 21:27 UTC
