### ISSUE TITLE
Need an equivalent to remove status check contexts API

### ISSUE THREAD

**Issue by RenukuntlaMonisha** [google/go-github#1771] opened 2021-01-04 14:12 UTC
I want to remove all the status checks that are added under my branch protection, to do so I tried using this `UPDATE` API call with the array of status checks as empty: https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#update-status-check-protection
but I'm not able to achieve what I wanted.
Then I tried using this recent `DELETE` API to remove status checks, 
https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#remove-status-check-protection
It worked but there is no equivalent function in this go package. Can you add the same?

**Comment by gmlewis** [comment] 2021-01-04 14:43
This appears to be a duplicate of #1770 .
If it is, can you please close it?
If not, can you please clarify what the difference are?

**Comment by gmlewis** [comment] 2021-01-07 17:37
Hearing no response, closing duplicate issue in favor of #1770.

**Closed by gmlewis** 2021-01-07 17:37 UTC
