### ISSUE TITLE
Add missing fields to MarketplacePlan and MarketplacePurchase structs

### ISSUE THREAD

**Issue by SudoVim** [google/go-github#1775] opened 2021-01-13 16:49 UTC
According to the GitHub documentation: https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#list-accounts-for-a-plan the "number" field is missing from MarketplacePlan, and the "updated_at" field is missing from MarketplacePurchase. I've already made these changes in my fork, so I'd like to submit a PR for review. However, it might take me a little while to get approval for this license agreement from my employer.

**Comment by gmlewis** [comment] 2021-01-13 17:18
Thank you, @SudoVim .

I'll open this up to any volunteer contributor so that you don't have to worry about making the PR yourself.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by chughpiyush** [comment] 2021-01-13 18:49
@gmlewis I can take up this one :)

**Comment by gunadhya** [comment] 2021-01-31 10:18
Hi @gmlewis, I'd like to work on this issue if it is available?

**Comment by gmlewis** [comment] 2021-01-31 13:59
Thanks, @gunadhya , but this issue is already assigned to @chughpiyush , so let's give an opportunity for a status update first.

**Comment by chughpiyush** [comment] 2021-01-31 18:20
@gmlewis I'll be giving a PR in a day or two.

**Comment by alexal** [comment] 2021-02-11 14:26
I haven't seen a PR yet, so I've decided to make a change myself. Please see PR #1798 and assign the issue to me. Thank you!

**Comment by gmlewis** [comment] 2021-02-11 14:46
> I haven't seen a PR yet, so I've decided to make a change myself. Please see PR #1798 and assign the issue to me. Thank you!

As described in #1798, this is not our standard way of proceeding (since the issue is already assigned), but in this case I'll allow it if you fix the PR problem, since it is a trivial change.

**Comment by gmlewis** [comment] 2021-02-11 14:53
Fixed by #1798.

**Closed by gmlewis** 2021-02-11 14:53 UTC
Labels: enhancement, good first issue
