### ISSUE TITLE
Closing a Pull Request Sends Back Validation Errors Related to Base Branch of PR

### ISSUE THREAD

**Issue by dumastaylorPFG** [google/go-github#2201] opened 2021-11-10 20:31 UTC
Closing a pull request via the "Update a Pull Request" end point https://docs.github.com/en/rest/reference/pulls#update-a-pull-request

Sending in a request body that only alters state yields an error message: 

`422 Unprocessable Entity: [{"message":"Validation Failed","errors":[{"message":"Ref must be a string","resource":"PullRequest","field":"base","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#update-a-pull-request"}]`

So, I went ahead and altered the flow to retrieve the pull request I am trying to close via the "Get a Pull Request" API call: https://docs.github.com/en/rest/reference/pulls#get-a-pull-request

Then, I made another attempt to close the PR, using a base value of the `base.ref` field in the response from the get-a-pull-request end point. Request body looked as follows:

{
   "state": "closed",
   "base": "main"
}

And the API again returned an error, informing me that I cannot update the base value of a closed PR. Error message:

`422 Unprocessable Entity: [{"message":"Validation Failed","errors":[{"message":"Cannot change the base branch of a closed pull request.","resource":"PullRequest","field":"base","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#update-a-pull-request"}]`

In both cases, the pull request I was trying to close does actually close. The API call is successfully updating the PR that I am asking it to update. 

This feels to me like a bug with the validation on the update pull request end point of the API. 

Please let me know if you are able to recreate the scenario/if there is any other helpful information I can provide. 

Thank you!

**Comment by gmlewis** [comment] 2021-11-10 20:46
Correct me if I'm wrong, but reading through your report and looking at the documentation of the used endpoints makes me think that this really should be a bug report filed against the GitHub v3 API itself, and that this is explicitly _not_ a bug of this Go client library.

If you agree, then please contact GitHub tech support with your bug report and we can leave this issue open until you hear back and update this issue with their response.

If you disagree, then please help me understand how this is truly a bug of this client library and not a bug of the GitHub v3 API.

Thanks.

**Comment by dumastaylorPFG** [comment] 2021-11-10 20:50
Thanks for the quick response Glenn. I do agree that this relates to the v3 API itself, not the Go client library. I have opened this issue in the incorrect place. I have no objection to this issue being closed....I will find the right avenue to report the issue to the API owners themselves.

Thanks again and apologies for the misunderstanding!

**Comment by gmlewis** [comment] 2021-11-10 20:52
> Thanks again and apologies for the misunderstanding!

No problem!  Thanks for reporting this to GitHub tech support.

I'll go ahead and close this, but still please feel free to report back your findings here to help others who are facing the same issue.

**Closed by gmlewis** 2021-11-10 20:52 UTC

**Comment by dumastaylorPFG** [comment] 2021-11-10 20:55
Sounds good - I've got a ticket open with support (looks like it's a personal ticket so I don't think I can share the link). I will share the results of what is found on this issue when more information comes to light.
