### ISSUE TITLE
[Question] How to mark a draft pull request as ready for review?

### ISSUE THREAD

**Issue by augustovictor** [google/go-github#2553] opened 2022-10-31 14:57 UTC
Sorry if I missed something, but could not find how to mark a draft pull request as ready for review. Any help on that?

Thanks in advance

**Comment by gmlewis** [comment] 2022-11-04 12:50
I think you simply remove the "Draft" flag and that marks it as ready for review.  Do you have a specific PR you are talking about?  The only draft I see is https://github.com/google/go-github/pull/2477 but that is not you, AFAICT.

**Comment by augustovictor** [comment] 2022-11-06 12:23
Hey @gmlewis . Thanks for your response.
I meant to do it programmatically. I managed to fetch the pull request I wanted to mark as ready for review. Tried using [this Edit method](https://github.com/google/go-github/blob/7a7a7f0943f3fcffc4b8f30feaaed7333b035a99/github/pulls.go#L332) but it has no `Draft` attr so I can set it to false.

**Comment by gmlewis** [comment] 2022-11-06 13:03
Ah, yes, it looks like we need to add it to the update struct. Do you want to create a PR, @augustovictor , or would you like me to open up this issue to other contributors to this repo?

**Comment by augustovictor** [comment] 2022-11-10 17:16
I'd love to contribute. However I don't have time to work on it 😞

**Comment by gmlewis** [comment] 2022-11-10 17:23
> I'd love to contribute. However I don't have time to work on it disappointed

No problem, @augustovictor !

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by alidevhere** [comment] 2022-11-21 17:12
Hii I would like to work on this issue. Please assign me this issue, i would love to work on it.

**Comment by gmlewis** [comment] 2022-11-21 17:29
> Hii I would like to work on this issue, please assign me this issue.

Thank you, @alidevhere ! The issue is yours.

**Comment by alidevhere** [comment] 2022-11-25 02:25
Hii i have tried the proposed solution but it does not seem to work 😢 .Adding Draft field in `pullRequestUpdate` struct does not update the draft Boolean. And i think the reason is this  [API](https://docs.github.com/en/rest/pulls/pulls#update-a-pull-request) only allow 5 fields to edit in pull request
title, body, state. base, maintainer_can_modify

**Comment by gmlewis** [comment] 2022-11-25 02:37
Ah!  I misread this documentation https://docs.github.com/en/rest/pulls/pulls#update-a-pull-request
above, and it looks like the official API does not let us update the "draft" status of a PR.

@alidevhere - can you please contact GitHub Tech Support and ask them how to handle this situation using the v3 API, and then report back here with your findings?  Feel free to point them to this issue.

**Comment by alidevhere** [comment] 2022-11-25 02:49
ok, I will do that

**Comment by alidevhere** [comment] 2022-11-25 16:20
@gmlewis Got this response from github support:

Thanks for reaching out to GitHub Support!

The REST API currently does not support converting draft pull request to ready-for-review. This is only available via [GraphQL API](https://docs.github.com/en/graphql/reference/mutations#markpullrequestreadyforreview)[1].

Please let me know if there are any additional questions you have on this.

Regards

Oluwaseun
GitHub Support

[1] https://docs.github.com/en/graphql/reference/mutations#markpullrequestreadyforreview

**Comment by gmlewis** [comment] 2022-11-25 21:13
Thank you, @alidevhere !

So it is not possible currently with the v3 API.

Closing issue as not possible.

**Closed by gmlewis** 2022-11-25 21:13 UTC
Labels: enhancement, good first issue

**Comment by alidevhere** [comment] 2022-11-25 21:15
@gmlewis  i was really excited for my first contribution to Open source 😞 . Can you please assign me some other task.

**Comment by gmlewis** [comment] 2022-11-25 21:23
> @gmlewis i was really excited for my first contribution to Open source 😞 . Can you please assign me some other task.

I suggest you read through the open issues and pick one that makes the most sense to you, then we can assign it as yours. 

If you have a Windows machine, I've got a bug in another repo that I'm having trouble figuring out if you would like to tackle that one instead. 😁

Thank you, @alidevhere !

**Comment by alidevhere** [comment] 2022-11-25 21:27
@gmlewis 
I have read but all good first issues are already assigned.

I wonder who still uses windows 🤔😂

**Comment by gmlewis** [comment] 2022-11-25 21:54
> @gmlewis I have read but all good first issues are already assigned.

OK, then if you are really motivated, you can take a look at the [GitHub blog](https://github.blog/) or [GitHub v3 API documentation](https://docs.github.com/en/rest), and study this code base, then figure out where this repo either differs from the official v3 API or where we have not yet implemented recent additions to the API... then create an issue and ask to be assigned to the issue that you create.

> I wonder who still uses windows :thinking: :joy: 

Not I.  :joy:
