### ISSUE TITLE
is_verified information not available in Organization struct

### ISSUE THREAD

**Issue by rnradon** [google/go-github#1573] opened 2020-07-14 17:05 UTC
When we call the REST API of GitHub `GET /orgs/:org` , the JSON response we get has a key call `is_verified`.
However, the same can not be found in the go-github package under the `Organization` struct.

**Comment by gmlewis** [comment] 2020-07-14 20:53
Thank you, @rnradon !

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by vikkyomkar** [comment] 2020-07-17 12:33
I would like to work on this issue

**Comment by itsksaurabh** [comment] 2020-07-17 17:52
@rnradon Are you referring to [this](https://github.com/google/go-github/blob/0683ca03b4e9f6cfab67a0f95f8c42bcacd57f6c/github/orgs.go#L49) specific field?

**Comment by gmlewis** [comment] 2020-07-18 11:54
Ah, thank you for the research, @itsksaurabh !  I didn't actually have time this week to investigate.
Closing as already Working As Intended.  Feel free to re-open if this didn't answer your question.

**Closed by gmlewis** 2020-07-18 11:54 UTC
Labels: enhancement, good first issue
