### ISSUE TITLE
Support for discussion_comment

### ISSUE THREAD

**Issue by lionelvillard** [google/go-github#2497] opened 2022-10-14 18:56 UTC
The event discussion_comment is not supported yet. See https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#discussion_comment for more information

**Comment by gmlewis** [comment] 2022-10-15 12:05
Thanl you, @lionelvillard . Would you like to create a PR to address this or would you like me to open this up to other contributors of this repo?

**Comment by qascade** [comment] 2022-10-17 15:01
Hi, if no body else is working on this. May I take a look at this issue?

**Comment by lionelvillard** [comment] 2022-10-17 15:20
thanks @qascade !!

**Comment by apurwaj2** [comment] 2023-02-24 22:35
I would like to take this up. I've already started working on it. Let me know if that should be okay.

**Comment by gmlewis** [comment] 2023-02-24 22:39
> I would like to take this up. I've already started working on it. Let me know if that should be okay. @gmlewis Could you please assign it to me?

@qascade - are you OK with this?

**Comment by qascade** [comment] 2023-02-24 22:51
Sure, should not keep blocked for long time. I suddenly got health emergency back when this was assigned to me. Couldn't pick it up again.

**Comment by gmlewis** [comment] 2023-02-25 00:44
> Sure, should not keep blocked for long time. I suddenly got health emergency back when this was assigned to me. Couldn't pick it up again.

Thank you, @qascade !
OK, @apurwaj2 - the issue is yours.  Thank you!

**Comment by gmlewis** [comment] 2023-02-25 00:45
Oh, and I hope you feel better fast, @qascade !

**Closed** 2023-03-06 17:43 UTC
Labels: enhancement, good first issue
