### ISSUE TITLE
`ListPullRequestsWithCommit` has incorrect option type

### ISSUE THREAD

**Issue by bennesp** [google/go-github#2815] opened 2023-06-20 12:49 UTC
I am currently using `PullRequests.ListPullRequestsWithCommit` to get a PR starting from a commit hash.

This function accepts a parameter "options" of type `PullRequestListOptions`. `PullRequestListOptions` has the `State` field along with many other fields, but `State` does not seem to do anything at all to the results of the function.

Example using commit sha cc8044e88926ef5b8ddb447c9a9fc5b2c8d6df4d (PR #2814, a merged PR from this repository):

```go
func main() {
	client := github.NewClient(nil)

	sha := "cc8044e88926ef5b8ddb447c9a9fc5b2c8d6df4d"
	options := &github.PullRequestListOptions{
		State: "open",
	}
	pull_requests, _, err := client.PullRequests.ListPullRequestsWithCommit(context.TODO(), "google", "go-github", sha, options)
	if err != nil {
		panic(err)
	}
	if len(pull_requests) == 0 {
		fmt.Println("no pull requests found")
		return
	}

	fmt.Printf("First PR: #%d\n", *pull_requests[0].Number)
}
```

This will print `First PR: #2814`, which seems to me to be incorrect because it is a **merged** PR, and thus its state is "closed", not "open".

This seems to be because this function uses the REST API `"repos/%v/%v/commits/%v/pulls"` under the hood, which, as stated [in the documentation](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-pull-requests-associated-with-a-commit), being an API from the Commits API, not from the Pull Request API, it does not have a `state` parameter.

**Comment by gmlewis** [comment] 2023-06-20 12:54
Thank you, @bennesp !
Do you want to create a PR to fix this, or shall I open this issue to other contributors to this repo?

**Comment by bennesp** [comment] 2023-06-20 12:57
Unfortunately, right now I don't think I am able to follow up on creating a PR for this, so I would rather open the issue to other contributors. If noone will pick this, then probably in the future I might have the chance to create a PR.

**Comment by RickleAndMortimer** [comment] 2023-06-20 13:08
Hey all, I'm interested in working on this issue

**Comment by gmlewis** [comment] 2023-06-20 13:11
> Hey all, I'm interested in working on this issue

Thank you, @RickleAndMortimer !
It's yours.

**Comment by vgnshiyer** [comment] 2023-06-28 03:38
I have a fix for this issue. @RickleAndMortimer Please let me know are you still working on it.
 
 I am happy to collaborate with you in fixing it.

**Comment by RickleAndMortimer** [comment] 2023-06-28 04:02
Hey @vgnshiyer! I'd love to chat with you about your process in fixing it. I've been struggling to work with Go for a bit now and I'm a bit busy right now so I'll let you know when we can talk more about it

**Comment by vgnshiyer** [comment] 2023-06-28 04:08
@RickleAndMortimer Sounds good.

**Comment by vgnshiyer** [comment] 2023-06-28 04:20
@gmlewis Can you please add me as an assignee to this issue?

**Comment by gmlewis** [comment] 2023-06-28 11:49
@vgnshiyer  - I can't add you, but I can make you the primary. Thank you for checking with @RickleAndMortimer first.  The issue is yours.

**Closed** 2023-07-03 13:25 UTC
Labels: bug, good first issue, Breaking API Change
