### ISSUE TITLE
Remove custom media type for Pull Request Reviews API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#638] opened 2017-05-11 16:29 UTC
The custom media type `application/vnd.github.black-cat-preview+json` can be removed from `go-github` as the "Pull Request Reviews API" is no longer in preview but has become official.

See GitHub Developer announcement:
https://developer.github.com/changes/2017-05-09-end-black-cat-preview/

**Comment by varadarajana** [comment] 2017-05-11 17:14
@gmlewis please assign this to me

**Comment by varadarajana** [comment] 2017-05-12 01:49
@gmlewis @shurcooL Pull Requests have three categories - Reviews, ReviewComments and Review Requests. Is this change required for all of them. The documentation points are reviews only.

**Comment by shurcooL** [comment] 2017-05-12 01:54
I think it's all endpoints that currently set the custom `application/vnd.github.black-cat-preview+json` Accept header. They no longer need to.

**Comment by swsnider** [comment] 2017-08-10 17:48
This change breaks Enterprise users -- we don't have reviews out of preview yet :(.

**Comment by shurcooL** [comment] 2017-08-10 18:28
Thanks for reporting @swsnider.

Re-opening for further consideration.

How should we go about dealing with this, @gmlewis?

A short term solution is to revert this removal of the preview API.

However, a long term solution is deciding on our policy. Should latest `master` target GitHub.com 
API only, or GitHub.com and GitHub Enterprise APIs? The challenge with doing the latter from what I can see is that their API chances/announcements are more difficult to track down for Enterprise API. But maybe I haven't looked hard enough.

**Comment by swsnider** [comment] 2017-08-10 18:30
The problem is that even after the Enterprise version with this fixed is released, you're typically still at the mercy of your IT org to upgrade your instance in a timely manner, so this may not be soluble by this project :(.

**Comment by shurcooL** [comment] 2017-08-10 18:39
Right. So it might be the case that a better/more viable solution is to, unfortunately, use an older version of go-github via vendoring.

**Comment by swsnider** [comment] 2017-08-10 18:49
Yeah, that's what I'm doing for now

**Comment by e-beach** [comment] 2017-08-20 17:04
I think the "good-for-beginners" label could be removed from this,

**Comment by gmlewis** [comment] 2017-08-21 19:40
I had a talk with @willnorris about this, and I believe our resolution was that semantic versioning (#376) would be the best way to support GitHub Enterprise API users (and that they would need to vendor the version that best supported their use-case), and that the latest `master` target the latest GitHub API.

As such, I think the "good-for-beginners" label still holds for this issue.

**Comment by willnorris** [comment] 2017-08-22 15:42
We can't help IT departments that are slow to upgrade, and vendoring (together with semver) is the right solution there.

But I kinda like the policy of not removing preview media types until they have been released in GitHub Enterprise (assuming we can track that without too much trouble).  We could go ahead and create issues like this when APIs come out of preview for github.com, and apply a special issue label, but don't actually remove the code.  Then, when the next GitHub Enterprise version is released, we go through the issues to see which ones we can remove.  It's a little bit of manual work but it's only done periodically.

**Comment by shurcooL** [comment] 2017-08-22 15:51
> As such, I think the "good-for-beginners" label still holds for this issue.

Note, the original task of removing the media type has already been done in 11516601ad905b8307923d093a487b6a5446f2c4, @gmlewis. I've reopened the issue only to discuss the outcome regarding Enterprise not having support for this yet. Aside from discussion, this issue isn't actionable, so I'll remove that label.

**Comment by shurcooL** [comment] 2017-08-22 16:16
It also sounds like we've come to a conclusion about the long term solution. Thanks @gmlewis and @willnorris. Further discussion about semver and tagging can be resumed in #376. I'll close this issue, but feel to continue discussion there, or open a new issue if there's something specific to address.

**Closed by shurcooL** 2017-08-22 16:16 UTC
