### ISSUE TITLE
github actions date not getting parsed by go-github

### ISSUE THREAD

**Issue by geekodour** [google/go-github#1254] opened 2019-08-18 20:01 UTC
github actions log:
```
19:45:30 main.go:110: parsing time ""8/18/2019 7:44:51 PM"" as ""2006-01-02T15:04:05Z07:00"": cannot parse "/2019 7:44:51 PM"" as "2006"
##[error]Docker run failed with exit code 1
```

this is on line `110`, `github.ParseWebHook` , it's working with any other payload if I just use it from a regular curl command. but it's failing when used with GithubActions.
```golang
data, err := ioutil.ReadFile(cmClient.inputFilePath)
if err != nil {
	log.Fatalln(err)
}
// Parsing event.json.
event, err := github.ParseWebHook("issue_comment", data)
if err != nil {
	log.Fatalln(err)
}
```

`data == issue_comment payload`

not sure if this is a github action issue or go-github issue. how can i help to resolve this?

**Comment by geekodour** [comment] 2019-08-18 20:02
@gmlewis any idea?

**Comment by gmlewis** [comment] 2019-08-19 13:47
You said that regular curl works... can you please provide an example of the response you get from curl?
Then we can look at how this repo is parsing that response and figure out what is going on.

**Comment by geekodour** [comment] 2019-08-19 14:06
@gmlewis 
this is the normal payload we're getting from the github api:
https://developer.github.com/v3/activity/events/types/#webhook-payload-example-14

the format is the exact same, but with the new github action it seems to be modifying the date I think.

**Comment by geekodour** [comment] 2019-08-19 14:13
for a temporary fix for this issue when using with the new github action was provided by @VladMasarik ,
```golang
// Temporary fix for the new Github actions time format. This makes the time stamps unusable.
txt := string(data)
reg := regexp.MustCompile("(.*)\"[0-9]+/[0-9]+/2019 [0-9]+:[0-9]+:[0-9]+ [AP]M(.*)")
txt = reg.ReplaceAllString(txt, "$1\"2019-06-11T09:26:28Z$2")
data = []byte(txt)
log.Println("temp fix active")
// End of the temporary fix

```

**Comment by VladMasarik** [comment] 2019-08-19 14:22
When we were using "previous" version of Github actions, the one where workflow was not described in `.yaml` files, the time stamp inside `event.json` file was following:
`2019-06-11T09:26:28Z`
However, after a the update the timestamp was following:
`8/18/2019 7:44:51 PM`

**Comment by geekodour** [comment] 2019-08-19 14:26
@parkr might have some inputs?

**Comment by gmlewis** [comment] 2019-08-19 14:26
Just to clarify, we have two things here... the actual response from the GitHub Developers API v3 and the `go-github` package (this repo).

When you say the `"previous" version of GitHub actions`, which of the two are you talking about?
If it is the latter, I know that we had a PR recently that changed the type of a timestamp to `time.Time`... but I want to verify if that's what we are talking about, please.

**Comment by gmlewis** [comment] 2019-08-19 14:28
Please take a look at https://github.com/google/go-github/pull/1179 and let me know if that is relevant.

**Comment by geekodour** [comment] 2019-08-19 14:39
`"previous" version of GitHub actions`

So github actions migrated from HCL to YAML syntax and had a lot of different changes with it.
https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax

When I was using `go-github` whith the GitHub Developers API v3 payload (`event.json` file in github actions) in the previous github actions (HCL Syntax) everything was working file. After github rolled out the new github actions (YAML syntax) the same code no longer works. (format of `event.json` is not the same anymore)

`event.json` is a normal GitHub Developers API v3 payload. but with the newer github actions this payload seems not to be compatible with `go-github` .  

About #1179  , 
https://github.com/google/go-github/blob/d77805f8bd2397c4e05eb160a78f92d89b1168dd/github/timestamp.go#L17

I don't think #1179 is causing this.

PS. The HCL syntax/YAML syntax does not make a difference in our context, i just used them to signal previous and the newer version of github actions

**Comment by parkr** [comment] 2019-08-19 14:56
Do you have a diff of the two JSON files, before vs after?

**Comment by VladMasarik** [comment] 2019-08-19 15:01
The #1179 is fairly similar to our case. However, instead of UNIX epoch integers, webhook payload in our case, is using this format `"created_at": "8/18/2019 7:44:51 PM"`

**Comment by geekodour** [comment] 2019-08-19 15:10
Oh yes, you're correct @VladMasarik ,  this definitely looks related to #1179

**Comment by gmlewis** [comment] 2019-08-19 15:51
Just FYI - a `Timestamp` is a `time.Time`:
https://github.com/google/go-github/blob/master/github/timestamp.go#L13-L19

So you should be able to format it anyway you wish.

**Comment by VladMasarik** [comment] 2019-08-19 16:50
[previous working](https://pastebin.com/y7e8zWHU)
[current broken parsing](https://pastebin.com/HNRdhY2c)
I am not sure if diff is useful here, as the webhook JSON is from two different repositories

**Comment by gmlewis** [comment] 2019-08-19 17:23
Hmmm... I remember that #1179 was created because the format changed.

I wonder if we need to be able to support both types of formats when parsing the timestamps?

(The other option might be for you to use the version of this repo before #1179 which would be:
https://github.com/google/go-github/releases/tag/v25.1.3 )

**Comment by ericsciple** [comment] 2019-08-19 21:20
@VladMasarik sorry about the regression. The timestamp from the event data was unintentionally getting mutated. The fix is merged into the production branch and should roll out with tomorrow's hotfix train.

**Comment by krasi-georgiev** [comment] 2019-08-19 21:43
The linked PR seems to be for a completely different api.

The problem is not with the go-github module, but the `/github/workflow/event.json` file that is generated by github actions.
https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/ 

The github api clearly shows that the expected date format returned by the github api is: 
`"created_at": "2011-04-10T20:09:31Z"`
https://developer.github.com/v3/issues/events/

but the date format in the json file generated by the github action is 
`"created_at": "8/18/2019 7:44:51 PM"`

That is why the go-github json parsing fails with:

```
data, err := ioutil.ReadFile("/github/workflow/event.json")
github.ParseWebHook("issue_comment", data)
```

**Comment by krasi-georgiev** [comment] 2019-08-19 21:44
@ericsciple thanks for the update

**Comment by gmlewis** [comment] 2019-08-20 01:41
So... can this issue be closed for this repo?

**Comment by srvaroa** [comment] 2019-08-21 23:49
@ericsciple it looks like the actions event payloads still carry the old format, can you confirm whether the fix was rolled out?

**Comment by ericsciple** [comment] 2019-08-22 00:42
@srvaroa sorry for the delay. The deployment rolled out to the first ring, but has not progressed further yet. My guess is it will deploy to the rest of the accounts tomorrow or Friday. I'll touch base with the folks driving the deployment tomorrow. Lots of relevant folks are at an all day event again tomorrow, so might be friday.

**Comment by srvaroa** [comment] 2019-08-22 20:45
Sorry for the spam, I didn't realize I was referencing this issue from the (WIP) commit :sweat:

**Comment by ericsciple** [comment] 2019-08-23 15:05
@VladMasarik @srvaroa the fix has rolled out everywhere now.

We tried to roll it out yesterday, but hit a snag during the deployment. Done now.

**Comment by srvaroa** [comment] 2019-08-23 19:03
Thanks @ericsciple! I verified on a test repo and I do get the expected timestamp format.

**Comment by gmlewis** [comment] 2019-08-23 19:15
Closing.

**Closed by gmlewis** 2019-08-23 19:15 UTC
