### ISSUE TITLE
bug: ListCommits filter by author not give correct answer

### ISSUE THREAD

**Issue by Yiyiyimu** [google/go-github#1826] opened 2021-03-22 15:55 UTC
I get contributor list with `ListContributors` API and when I try to get commits of each contributor, I found some of them have zero commits.

For example, we could see `sarraz1` got [one commit](https://github.com/Kong/kong/commit/4e2e1d7a81748c41e5bd3b55cc4b6f4ae137b727) in `kong/kong`,
 but when do `ListCommits` filter by author gave me nothing back, which seems weird to me.

I believe this is a Github side error since I reproduce it in bare Github API, but since I noticed there are label `Waiting for Github`, so maybe I could get some help from the community

A ready to run demo:
```
package main

import (
	"context"
	"fmt"

	"github.com/google/go-github/v33/github"
)

func main() {
	ctx := context.Background()

	client := github.NewClient(nil)

	owner := "kong"
	repo := "kong"
	author := "sarraz1"

	listCommitOpts := &github.CommitsListOptions{Author: author, ListOptions: github.ListOptions{PerPage: 100}}
	commits, resp, err := client.Repositories.ListCommits(ctx, owner, repo, listCommitOpts)
	if err != nil {
		panic(err)
	}
	fmt.Printf("commits num: %d\n", len(commits))
	fmt.Printf("%#v\n", resp)
}
```

**Comment by gmlewis** [comment] 2021-03-22 19:47
@Yiyiyimu - Isn't this a duplicate of #1825 ?  If so, please close it to avoid confusion, or I will if I don't hear back from you.

**Comment by Yiyiyimu** [comment] 2021-03-23 02:04
Hi @gmlewis actually no, it's just another problem I came across 🤣

**Comment by gmlewis** [comment] 2021-03-23 14:12
OK, but just FYI, the "issues" here are only used to track issues relating to this repo, and we do not track GitHub issues, so I'll close this issue, but please feel free to update the comments after you hear back from GitHub tech support.

**Closed by gmlewis** 2021-03-23 14:12 UTC
